数值类型的 :
        1. 归一化 *
        2. 标准化 *
         (1,2重点)
        3. 缺失值
类别型 : one-hot
时间类型 : 时间的切分

X' = (x - min)/(max - min)
X'' = X' * (mx - mi) + mi
   : 针对列处理, max为一列的最大的, min为最小的, mx与mi为指定区间默认mx = 1, mi = 0

归一化的API : MinMaxScaler : 每个特征缩小的范围

In [58]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.impute import SimpleImputer
import numpy as np

In [59]:
def mm():
    """
    归一化
    return : None
    """
    # feature_range : 范围
    mm = MinMaxScaler(feature_range=(2, 3))
    data = mm.fit_transform([[90,2,10,40],[60,4,15,45],[75,3,13,46]])
    
    print(data)
    
    return None

In [60]:
if __name__ == "__main__":
    mm()

[[3.         2.         2.         2.        ]
 [2.         3.         3.         2.83333333]
 [2.5        2.5        2.6        3.        ]]


标准化: 
    公式 : X = (x - mean)/σ # σ是标准差
    ( 适大量的数据

In [61]:
def stand():
    """
    标准化缩放
    """
    std = StandardScaler()
    data = std.fit_transform([[1,-1,3],[2,4,2],[4,6,-1]])
    print(data)
    return None

In [62]:
if __name__ == "__main__":
    stand()

[[-1.06904497 -1.35873244  0.98058068]
 [-0.26726124  0.33968311  0.39223227]
 [ 1.33630621  1.01904933 -1.37281295]]


对缺失值的处理
inputer(miss_values ='np.nan', strategy='mean',axis=0)
NAN是float型

In [111]:
def SI():
    """
    缺失值处理
    """
    SI = SimpleImputer(missing_values=np.nan, strategy='mean')
    # fit_trasform 的输入需要是numpy
    X = [[1,2], [np.nan, 3], [7,6]]
    data = SI.fit_transform(X)
    print(data)
    return None

In [112]:
if __name__ == '__main__':
    SI()

[[1. 2.]
 [4. 3.]
 [7. 6.]]
